---
- name: "ETAPA 1: Instalar dependências essenciais do sistema"
  apt:
    name:
      - ufw
      - zip
      - unzip
      - apt-transport-https
      - debian-keyring
      - debian-archive-keyring
    state: present
    update_cache: yes
  become: yes

- name: "ETAPA 2: Configurar o Firewall (UFW)"
  block:
    - name: "Permitir portas essenciais para Docker e SSH"
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "22"  # SSH
        - "80"  # HTTP (para Caddy)
        - "443" # HTTPS (para Caddy)
    
    - name: "Habilitar o UFW"
      community.general.ufw:
        state: enabled
  become: yes

- name: "ETAPA 3: Instalar Docker e dependências"
  block:
    - name: "Adicionar a chave GPG oficial do Docker"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Adicionar o repositório do Docker"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: "Instalar Docker e Docker Compose"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: "Garantir que o serviço Docker esteja ativo"
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: "Adicionar usuário 'ubuntu' ao grupo 'docker'"
      user:
        name: ubuntu
        groups: docker
        append: yes

- name: "ETAPA 4: Preparar e Implantar a Stack Docker"
  block:
    - name: "Criar diretórios para a configuração do Docker"
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop:
        - /home/ubuntu/foundry-docker
        - /home/ubuntu/foundry-docker/caddy

    - name: "Copiar o arquivo foundryvtt.zip para o servidor (se necessário)"
      copy:
        src: foundryvtt.zip
        dest: /tmp/foundryvtt.zip
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      when: foundry_vtt_download_url is not defined or foundry_vtt_download_url | length == 0

    - name: "Gerar o arquivo Caddyfile a partir do template"
      template:
        src: Caddyfile.j2
        dest: /home/ubuntu/foundry-docker/caddy/Caddyfile
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      when: domain_name is defined and domain_name|length > 0

    - name: "Gerar o arquivo docker-compose.yml a partir do template"
      template:
        src: docker-compose.yml.j2
        dest: /home/ubuntu/foundry-docker/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: "Iniciar a stack de serviços com Docker Compose"
      community.docker.docker_compose:
        project_src: /home/ubuntu/foundry-docker
        state: present
